# Generated by Django 4.2.6 on 2023-10-20 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda_app', '0004_userprofile_uri_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='encargado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_tiendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uri_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
