# Generated by Django 4.2.6 on 2023-10-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0006_categoria_producto_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
