# Generated by Django 4.2.6 on 2023-10-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0007_remove_producto_categorias_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
