# Generated by Django 4.2.6 on 2023-11-16 16:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0010_userprofile_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='productos/'),
        ),
    ]
