# Generated by Django 4.2.6 on 2023-11-16 16:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0011_producto_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='post_image',
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 700], upload_to='productos/'),
        ),
    ]
