# Generated by Django 4.2.6 on 2023-12-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0013_producto_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True, help_text='Si el producto es visible se mostrará en la tienda online.', verbose_name='Visible'),
        ),
    ]
