# Generated by Django 4.2.6 on 2023-12-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0014_alter_producto_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
