# Generated by Django 4.2.6 on 2023-12-21 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0022_alter_tienda_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='a',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
