# Generated by Django 4.2.6 on 2023-12-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0023_producto_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='a',
        ),
    ]
