# Generated by Django 4.2.6 on 2023-12-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0024_remove_producto_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='parent_comment', to='tienda_app.comment'),
        ),
    ]
