# Generated by Django 4.2.6 on 2023-12-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0026_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
    ]
