# Generated by Django 4.2.6 on 2024-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0027_remove_comment_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vnumerico', models.IntegerField(blank=True, null=True, verbose_name='Valor si es un número')),
                ('vtexto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor si es un texto')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Preferencias',
            },
        ),
    ]
