# Generated by Django 4.2.6 on 2024-01-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0029_tienda_latitude_tienda_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='provincia',
            field=models.CharField(blank=True, choices=[('pinar_del_rio', 'Pinar del Río'), ('artemisa', 'Artemisa'), ('la_habana', 'La Habana'), ('mayabeque', 'Mayabeque'), ('matanzas', 'Matanzas'), ('cienfuegos', 'Cienfuegos'), ('villa_clara', 'Villa Clara'), ('sancti_spiritus', 'Sancti Spíritus'), ('ciego_de_avila', 'Ciego de Ávila'), ('camaguey', 'Camagüey'), ('las_tunas', 'Las Tunas'), ('granma', 'Granma'), ('holguin', 'Holguín'), ('santiago_de_cuba', 'Santiago de Cuba'), ('guantanamo', 'Guantánamo')], max_length=100),
        ),
    ]
