# Generated by Django 4.2.6 on 2024-01-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0032_comment_super_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='super_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
