# Generated by Django 4.2.6 on 2024-01-30 00:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0033_alter_comment_super_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='images/default.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1000, 700], upload_to='avatars/'),
        ),
    ]
